# Copy from the Wordpress Dockerfile
# updateted sections are: 
# "Processwire Dowload Part"

FROM nginx:latest

MAINTAINER kreativmonkey <webmaster@calyrium.org>

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
#RUN { \
#		echo 'opcache.memory_consumption=128'; \
#		echo 'opcache.interned_strings_buffer=8'; \
#		echo 'opcache.max_accelerated_files=4000'; \
#		echo 'opcache.revalidate_freq=60'; \
#		echo 'opcache.fast_shutdown=1'; \
#		echo 'opcache.enable_cli=1'; \
#	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

VOLUME /usr/share/nginx/

RUN apt-get update && apt-get -y upgrade \
	&& apt-get install -y pwgen curl unzip php5-fpm php5-mysql php-apc php5-cli \
	 	php5-curl php5-gd php5-mcrypt php5-intl php5-imap php5-tidy php5-imagick \
		php5-memcache php5-xmlrpc php5-xsl php5-mysql 

ADD nginx.conf /etc/nginx/nginx.conf

# Download Processwire, check and install
ENV PROCESSWIRE_STACKE master
ENV PROCESSWIRE_SHA1 bfde25a27432509dd060ff39a4e5aa8a71666fac
ENV NGINX_PATH /usr/share/nginx

RUN curl -o processwire.zip -SL https://github.com/ryancramerdesign/ProcessWire/archive/${PROCESSWIRE_STACKE}.zip \
	&& echo "$PROCESSWIRE_SHA1 *processwire.zip" | sha1sum -c - \
	&& unzip processwire.zip -d ${NGINX_PATH}/ \
	&& rm processwire.zip \
	&& mv ${NGINX_PATH}/ProcessWire-${PROCESSWIRE_STACKE} ${NGINX_PATH}/www \
	&& mv ${NGINX_PATH}/www/site-beginner ${NGINX_PATH}/www/site \
	&& rm -rf ${NGINX_PATH}/www/site-* \
	&& chown -R www-data:www-data ${NGINX_PATH}/www

CMD ["php-fpm"]
